name: build and push docker image
description: this will build and push docker image

inputs:
  IMAGE_NAME:
    description: docker image name
    required: true
  WORKING_DIR:
    description: working dir of micro service
    required: true
  ADDITIONAL_ARGS:
    description: additional args for builing the image
    required: false
    default: ''
  DOCKERHUB_USERNAME:
    description: docker user for login
    required: true
  DOCKERHUB_TOKEN:
    description: docker access token to login
    required: true

outputs:
  IMAGE:
    description: final image name
    value: ${{ steps.docker-push.outputs.IMAGE }}

runs:
  using: composite

  steps:
    - id: docker-login
      name: docker login
      uses: docker/login-action@v4
      with:
        username: ${{inputs.DOCKERHUB_USERNAME}}
        password: ${{inputs.DOCKERHUB_TOKEN}}

    - id: docker-build-image
      name: docker build image
      shell: bash
      working-directory: ${{inputs.WORKING_DIR}}
      run: docker build -t ${{inputs.IMAGE_NAME}}:${{github.sha}} ${{inputs.ADDITIONAL_ARGS}} .

    - id: docker-list-image
      name: docker info
      shell: bash
      run: docker images

    - id: docker-push
      name: docker push image
      shell: bash
      run: |
        docker push ${{inputs.IMAGE_NAME}}:${{github.sha}}
        echo "IMAGE=${{inputs.IMAGE_NAME}}:${{github.sha}}" >> $GITHUB_OUTPUT
